### PR TITLE
fix(?) Jim Gough's info

### PR DESCRIPTION
**Pull request by evanchooly**

### CODE REVIEW

**Comment by aalmiray** [comment]
Justin, I'm afraid Jim's link must remain as it is due to a "slight" problem of rendering underscore characters by Asciidoc. Dan Allen suggested 2 approaches, using an attribute as was the least invasive option.

**Comment by evanchooly** [comment]
Ok. I'll manually add his to the list then

**Comment by evanchooly** [comment]
Does the rendering matter so much if the link itself is still valid?

**Comment by aalmiray** [comment]
That's the thing, both the link ref and text are rendered incorrectly 🤷‍♂️

**Comment by evanchooly** [comment]
Ah. It looked fine in the Idea renderer.

**Pull request closed without merging**
