### PR TITLE
Update Bluesky handles

### PR DESCRIPTION
**Pull request by hsz**

### CODE REVIEW

**Comment by aalmiray** [comment]
@hsz looks like the base branch was modified in between and can't merge as is. Would you be able to rebase and resubmit on your side? Thank you 😅

**Comment by hsz** [comment]
@aalmiray I believe it's all good now!

**Comment by aalmiray** [comment]
@hsz strange. I still get the following message after your last commit

“This branch cannot be rebased safely
Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge.”

I may need to have a look at this PR on my computer instead of using the mobile app 🤷‍♂️

**Comment by aalmiray** [comment]
Thank you 🎉

**Comment by henri-tremblay** [comment]
Thanks for magically adding me.

**Pull request closed without merging**
