### PR TITLE
Add Mastodon column

### PR DESCRIPTION
**Pull request by alblue**
This adds a new column, suitable for populating with Mastodon links (see http://joinmastodon.org for more information)

### CODE REVIEW

**Comment by aalmiray** [comment]
Perhaps it should be better with just one "Social" column. That way anyone may add as many social links as wanted. WDYT?

**Comment by evanchooly** [comment]
I'll need to update the JC list generator so just let me know what the final decision is.

**Comment by aalmiray** [comment]
@evanchooly do you need an unambiguous way to locate twitter links/handles? If so we'll have to either use separate columns OR perhaps a prefix such as `twitter:@foo` or similar. If the latter we'll have to agree on the prefix for each social link.

**Comment by evanchooly** [comment]
probably just a prefix would do.  separate columns would easier for me but if we're supporting 2 social networks, we might as well support 3.  And if we support 3, ...

I don't have a strong preference either way.  We're unlikely to run in to that problem but using the labeled approach it's built in and we don't have to care.

**Comment by alblue** [comment]
Note that 'mastodon' isn't a singleton service; there are many of them, so you need the host in there as well. For example, there's `mastodon.social`, `mastodon.online`, `mas.to` etc.

https://joinmastodon.org/communities/general

**Comment by alblue** [comment]
(I've suggested to Sharat that maybe having a `mastodon.java` server would be a great way of providing something that the Java community to gravitate towards ...)

**Comment by aalmiray** [comment]
@alblue I guess that would rule out using `mastodon:` as a prefix in case someone would like to use several Mastodon servers, right?

**Comment by alblue** [comment]
Well, you could have a `mastodon:` prefix and then require all the identifiers to be given as `@alblue@mastodon.social` which is the preferred way of representing the handle, and then expand it into https://mastodon.social/@alblue automatically.

You could just use a single Social column but have a Unicode emoji to disambiguate eg 🐧 or 🐘 for the different versions for Twitter and mastodon respectively. You might also be able to merge in the LinkedIn which some use as hyperlinks on their names in the same social column.

**Comment by aalmiray** [comment]
@alblue ah emojis would make it better from a visual POV. @evanchooly WDTY?

**Comment by evanchooly** [comment]
all *I* really need is some way to denote the twitter links to extract.  i don't really have an opinion on the mastodon bits.

**Comment by alblue** [comment]
> all *I* really need is some way to denote the twitter links to extract.  i don't really have an opinion on the mastodon bits.

You could just grep for "Twitter.com" :-)

By the way, one advantage of having link: is that it's an http link understood by browsers and clickable from the web interface and local clones. If you are storing other links in the asciidoc file but they aren't http ones then people won't be able to go to the GitHub interface and click on it directly.

**Comment by aalmiray** [comment]
Very well. Then I propose the following:

1. Keep just **1** column for social links. Rename header to `Social`.
2. Each social link must be prefixed with an emoji. 🐘 (mastodon) 🐧 (twitter) 🔗 (linkedin) 📝 (blog). We can decide which other emojis to use later. These emojis and their meaning should be defined in a table at the top of the readme.
3. Each social link should be place in their own row/line. Use `+` at the end of the line to split, such as
```
| 🐧 link:https://twitter.com/aalmiray[@aalmiray] +
  📝 link:https://andresalmiray.com[]
```

**Comment by aalmiray** [comment]
We've got this covered with the new YAML file.

**Pull request closed without merging**
