### PR TITLE
I Retired

### PR DESCRIPTION
**Pull request by ewolff**

### CODE REVIEW

**Comment by aalmiray** [comment]
Instead of deleting the entry, should we have an additional mark (like we do for deceased, alumnus) to signal a retired JC?

cc: @kabutz

**Comment by myfear** [comment]
+1 for a new status!

**Comment by kabutz** [comment]
Since this list is probably the only definitive list (thanks Oracle for dropping the ball on this one) we need to be very sure to delineate active and non-active members. IIRC we had four folks who wanted to leave - Rickard, Jeff (although maybe only the mailing list), Crazy Bob (when Hani was not accepted) and now Eberhard. Maybe cross out their names?

**Comment by henri-tremblay** [comment]
I think RIP and retired marks are interesting unless the person concerned doesn't want to. We always have the git history in case of needs.

**Comment by aalmiray** [comment]
I think it's a good idea to have an additional mark for retired JCs. Personally I've seen the JC award as a lifetime award. It's granted based on the merits up to the nomination. Many JCs continue to champion Java, others move away to other endeavors yet they remain JCs because what they do today does not change what they did in the past for the Java Community. 

This being said, as much as I like the idea of using an additional mark I also think respecting @ewolff wishes is more important. Thus @ewolff, how would you like to proceed?

**Comment by ewolff** [comment]
Thanks for reaching out - I would be very happy to remain in the list as former champion. It is an honor to have been part of the group. I couldn't figure out a way to do that so that is why I just removed myself.

**Comment by aalmiray** [comment]
Very well. In that case I'll close this PR and add a new mark.

**Comment by ewolff** [comment]
Great, thanks! 🙂

**Pull request closed without merging**
