### PR TITLE
Updated socials, this time w/o distractions

### PR DESCRIPTION
**Pull request by mkheck**

### CODE REVIEW

**Comment by aalmiray** [comment]
Xing is not supported. I admire your enthusiasm though 😅

**Comment by aalmiray** [comment]
Sadly, no. Your PR broke the site workflow due to strict schema checks we have in place.

**Comment by aalmiray** [comment]
I just pushed an update to support Xing. Next time, please read the header found at https://github.com/aalmiray/java-champions/blob/main/java-champions.yml 😉

**Comment by mkheck** [comment]
Oh no! I honestly figured there would be something equivalent to JsonIgnoreProperties(ignoreUnknown=true) in the yaml parsing logic. Very sorry about breaking the build, that never even crossed my mind. 😬

Thanks for doing the often-thankless work to keep the list up to date and alive, @aalmiray!

**Pull request merged**
