### PR TITLE
mauricenaftalin-bluesky

### PR DESCRIPTION
**Pull request by MauriceNaftalin**

### CODE REVIEW

**Comment by aalmiray** [comment]
@MauriceNaftalin this PR has for 4 commits but no changes 😅

**Comment by aalmiray** [comment]
I've manually updated your info 😏

**Comment by MauriceNaftalin** [comment]
Thank you very much!  But I suppose I’d better know: what did I do wrong?

≈M≈


Le 3 déc. 2024 à 11:55:17, Andres Almiray ***@***.***> a
écrit :

**Comment by aalmiray** [comment]
I don't know exactly. It seems you merged two PRs on your fork before sending a PR to this repository. 

Usually just editing the file on the browser and adding a single commit PR is enough.

**Comment by MauriceNaftalin** [comment]
OK, I think I understand what particular kind of a dog’s dinner I made of
it. Thanks for sorting it out for me!  I’m safely on Bluesky now: let’s
hope it stays a better home than the one we came from.


≈M≈

Le 3 déc. 2024 à 14:03:33, Andres Almiray ***@***.***> a
écrit :

**Pull request closed without merging**
